baseURL: http://blog.mgechev.com/
disablePathToLower: true
languageCode: en-us
title: Minko Gechev's blog
googleAnalytics: "UA-18060688-3"
theme: "minimalist"
pygmentsCodeFences: true
pygmentsCodeFencesGuessSyntax: true
pygmentsUseClasses: true

params:
  bio: "Co-founder & CTO at Rhyme.com"
  description: "The official blog of Minko Gechev"
  author: "Minko Gechev"
  twitter: mgechev
  enableRSS: true
  enableGoogleAnalytics: true
  enableDisqus: true
  disqusShortname: mgechev
  socialIconStyle: ""
  iconFont: "font-awesome"

social:
  twitter: "https://twitter.com/mgechev"
  github: "https://github.com/mgechev"
  stack-overflow: "https://stackoverflow.com/users/1106382/minko-gechev"
  