name = "Aglaus"
license = "MIT"
licenselink = "https://github.com/dim0627/hugo_theme_aglaus/blob/master/LICENSE.md"
description = "Theme for Hugo that supports the Accelerated Mobile Pages Project(AMP)."
homepage = "https://github.com/dim0627/hugo_theme_aglaus"
tags = ["blog", "amp"]
features = ["amp", "responsive", "seo", "thumbnail", "share button", "structured data", "ogp", "twitter cards"]
min_version = 0.16

title = "Minko Gechev's Blog"

googleAnalytics = "UA-18060688-3" # Optional

[params]
  dateformat = "Jan 2, 2006" # Optional
  latestSize = 4 # Optional
  ampscripts = """ # Optional, scripts for AMP.
<script async custom-element="amp-twitter" src="https://cdn.ampproject.org/v0/amp-twitter-0.1.js"></script>
<script async custom-element="amp-iframe" src="https://cdn.ampproject.org/v0/amp-iframe-0.1.js"></script>
<script async custom-element="amp-ad" src="https://cdn.ampproject.org/v0/amp-ad-0.1.js"></script>
"""